### PR TITLE
Image definitions with one size in editor

### PR DESCRIPTION
**Pull request by timatron**
working on a fix for non-multi size images for editor

### CODE REVIEW

**Comment by davisshaver** [comment]
Looking good so far. Noticed just one flow issue. Inline alignment control works fine, but clicking the edit button breaks sizing.



I'm trying to figure out if this is an AFT or Photonfill issue.

When the media template is used in backbone on inline edit, the attachment is missing. 

screen shot 2016-12-28 at 9 19 09 am

Compared to no Photonfill.

screen shot 2016-12-28 at 9 22 42 am

Trying to debug this now.

**Comment by davisshaver** [comment]
After looking into this, I think it's related to the classes on the image tag, going to work on a PR.

**Comment by davisshaver** [comment]
@timatron Wanna look at this add-on? https://github.com/alleyinteractive/photonfill/pull/61

**Comment by willgladstone** [comment]
Looks good :horse:

**Pull request merged**
